apiVersion: tracee.aquasec.com/v1beta1
kind: Policy
metadata:
	name: overview-policy
	annotations:
		description: sample overview policy
spec:
	scope:
	  - global
	rules:
	  - event: security_file_open
	    filters:
		- data.pathname=*tmp/*
